### PR TITLE
added it-IT

### PR DESCRIPTION
**Pull request by JtheBAB**
Dictionary was copied from: https://ckeditor-spellcheck.nanospell.com/ckeditor-spellchecking-dictionaries

I have tested with the CLI tool and it works.

### CODE REVIEW

**Comment by jfmdev** [comment]
The `it-IT.txt` file has lines with some kind of metadata which should be removed. For example:

```
#h0|w0
+++++++++
+++++++++
+++++++++
+++++++++
+++++++++
```

or

```
BRB#b1111|b1214|b1250|b1258|b1285|b3135|b4248|b4259|b4262|b7647|b7654
BRBB#b1215|b1216
BRBF#b1220|b1221|b1268|b1269|b1270|b1271|b1272
BRBJ#B12|b1222|b1286|b1287|b1288|b1289
BRBK#b1217|b1218|b1219|b1223|b1224|b1251|b1259|b1260|b1261|b1262|b1263|b1273|b1274|b1299|b1300|b1301|b1302|b1303|b1304|b1305|b1306|b1307|b5683|b5684|b5685|b5686|b5687|b5688|b5689|b5690|b5691
BRBL#b1308|b1309|b1526
BRBN#b1225|b1275|b1276|b1277|b1278|b1290|b1291|b1292|b4249|b4250|b4251|b4252|b4253|b4254|b4255|b4256|b4257|b4258|b4263|b4264|b4265|b4266|b4267|b4268|b4269|b4270|b4271|b4272|b4273|b4274|b4275|b5692|b5693|b5694|b5695|b6024|b7648|b7649|b7650|b7651|b7652|b7653
BRBR#b1226|b1227|b1228|b1229|b1230|b1231|b1232|b1233|b1234|b1235|b1236|b1237|b1238|b1239|b1240|b1241|b1252|b1253|b1254|b1255|b1264|b1265|b1266|b1267|b3080|b3081|b3082|b3083|b3104|b3136|b4260|b4261|b5696|b5697|b7655|b7656|b7657|b7658
BRBS#b1242|b1243|b1248|b1249|b1293|b1294|b1295|b1296|b1297|b1298|b1310|b1311
BRBT#B11|B13|b1244|b1245|b1246|b1247|b1256|b1257|b1279|b1280|b1281|b1282|b1283|b1284|b1312|b1313|b1314|b1315|b5698|b5699|b5700|b5701|b5702|b5703|b5704|b5705|b5706|b5707|b5708|b5709|b5710|b5711|b5712|b5713|b5714|b5715|b5716|b5717|b5718|b5719|b5720|b5721|b5722|b5723|b5724|b5725|b5726|b5727|b5728|b5729|b5730|b5731|b5732|b5733|b5734|b5735|b5736|b5737|b5738|b5739|b5740|b5741|b5742|b5743|b5744|b5745
```

or

```
MRNM#m2589|m2635
MRNN#m2590|m2591|m2592|m2637|m2767|m2768
MRNR#m2593|m2594|m2595|m2596|m2597|m2598|m2599|m2600|m2601|m2620|m2621|m2622|m2623|m2624|m2625|m2626|m2627|m2628|m2629|m2630|m2631|m2632|m2633|m2769|m2777|m2778
MRNS#m2602|m2603|m2604|m2605|m2606|m2607|m2638|m2639|m2640|m2641|m2642|m2779|m2780|m2781|m2782|m2804|m2805|m8342
MRNT#m2608|m2609|m2610|m2611|m2612|m2636|m2650|m2651|m2652|m2653|m2654|m2655|m2656|m2657|m2658|m2770|m2771|m2772|m2773|m2774|m2794|m2795|m2796|m2811|m2812|m4509|m4510|m4511|m4512|m6379|m6380|m6381|m6383|m6384|m8232|m8338|m8344|m8345
```

**Comment by JtheBAB** [comment]
I looked at the sv-SE as a template. I removed now (hopefully) everything.

**Comment by JtheBAB** [comment]
@jfmdev

Would it be possible to merge all 3 pull request and release a new version?

Thank you

**Comment by jfmdev** [comment]
Sorry for the late response.

It seems the first 123 lines of the file still contains some invalid data:

```
0
0
002
0180
0504
060
07
0840
087
1
1
1013
1070
1129
11484
1166
12584
1304
135
1412
1560
1656
1666
17
17572
1824
19
1afta
2
2
2
2
2
2057
206
22106
22165
22713
2549
2669
287
3
3
3049
31
324
325
3318
3334
3396
3456
36
368
3707
3847
388
3940
40
40
4081
414
422
438
4471
4738
485
4855
4903
4938
5
5
507
5433
5572
5689
58
6
6
60
601
605
63
6448
664
6921
7
70
72
723
75
7588
76
7938
7953
8
8043
821
83
85
8567
87
874
8813
8822
9
9
9
9
9
9
91
9193
92
92
92
9428
95
959
9624
978
9853
99
a31586
```

**Comment by JtheBAB** [comment]
@jfmdev 

I'm sorry. Now it should be fine.

**Comment by jfmdev** [comment]
Thanks!

**Pull request merged**
